### ISSUE TITLE
Says that Chrome on Windows does support emoji whereas clearly it doesn't

### ISSUE THREAD

**Issue by botanicus** [danalloway/detect-emoji-support#3]
[See here](https://www.dropbox.com/s/xzjfgtcscu16wlh/2020-01-23%2010.31.10.jpg?dl=0)

**Comment by danalloway** [comment]
using the same OS/Browser combo, go here and screenshot the output for me please: https://codepen.io/danalloway/pen/VwYNOwL

**Comment by botanicus** [comment]
![0B6D8EE1-AA18-4DE7-9E84-7DA6462A6767](https://user-images.githubusercontent.com/6171/74054081-e09aea80-49a2-11ea-9308-af5aee36c472.jpeg)

**Comment by danalloway** [comment]
so that CodePen was the raw Modernizer emoji detection script
it shows that the browser you're using does support emojis, based on how it's detecting the capabilities.

why your browser is not rendering them properly is beyond me, but all my repo does is port the Modernizer script so there is not much I can support on my end beyond that (as I didn't write any of it)

thanks for your help in tracking this down, if I figure anything out i will update it on here
